services:
  nats-server:
    image: nats:latest
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-storage:/data

  admin-api:
    build:
      context: ./admin-api
      dockerfile: Dockerfile
    environment:
      - NATS_URL=nats://nats-server:4222
    ports:
      - "5001:5001"
    depends_on:
      - nats-server

  frontend-api:
    build:
      context: ./frontend-api
      dockerfile: Dockerfile
    environment:
      - NATS_URL=nats://nats-server:4222
    ports:
      - "5000:5000"
    depends_on:
      - nats-server

volumes:
  nats-storage:
